const performance = [
    {
        performanceNum: "0",
        band: "Bush",
        venue: "Deer Creek/Verizon/Klipsch/Ruoff",
        city: "Noblesville",
        state: "IN",
        date: "8/12/1995",
        notes: "X-Fest 1995",
        sample: "https://www.youtube.com/watch?v=Opp9P6k9z-I&list=RDOpp9P6k9z-I&start_radio=1",
    },
        {
        performanceNum: "1",
        band: "Sponge",
        venue: "Deer Creek/Verizon/Klipsch/Ruoff",
        city: "Noblesville",
        state: "IN",
        date: "8/12/1995",
        notes: "X-Fest 1995",
        sample: "https://www.youtube.com/watch?v=OGKRr0NmgFM&list=RDOGKRr0NmgFM&start_radio=1",
    },
        {
        performanceNum: "2",
        band: "Sugar Ray",
        venue: "Deer Creek/Verizon/Klipsch/Ruoff",
        city: "Noblesville",
        state: "IN",
        date: "8/12/1995",
        notes: "X-Fest 1995",
        sample: "https://www.youtube.com/watch?v=urtics-WToY&list=RDurtics-WToY&start_radio=1",
    },
        {
        performanceNum: "3",
        band: "Toadies",
        venue: "Deer Creek/Verizon/Klipsch/Ruoff",
        city: "Noblesville",
        state: "IN",
        date: "8/12/1995",
        notes: "X-Fest 1995",
        sample: "https://www.youtube.com/watch?v=45aDr01ZyPg&list=RD45aDr01ZyPg&start_radio=1",
    },
        {
        performanceNum: "4",
        band: "Weezer",
        venue: "Deer Creek/Verizon/Klipsch/Ruoff",
        city: "Noblesville",
        state: "IN",
        date: "8/12/1995",
        notes: "X-Fest 1995",
        sample: "https://www.youtube.com/watch?v=OoPHItnUFkw&list=RDOoPHItnUFkw&start_radio=1",
    },
        {
        performanceNum: "5",
        band: "Everclear",
        venue: "Deer Creek/Verizon/Klipsch/Ruoff",
        city: "Noblesville",
        state: "IN",
        date: "8/10/1996",
        notes: "X-Fest 1996",
        sample: "https://www.youtube.com/watch?v=qHLAAFIg7oM&list=RDqHLAAFIg7oM&start_radio=1",
    },
        {
        performanceNum: "6",
        band: "Goldfinger",
        venue: "Deer Creek/Verizon/Klipsch/Ruoff",
        city: "Noblesville",
        state: "IN",
        date: "8/10/1996",
        notes: "X-Fest 1996",
        sample: "https://www.youtube.com/watch?v=L2ziJW-NHHs&list=RDL2ziJW-NHHs&start_radio=1",
    },
        {
        performanceNum: "7",
        band: "No Doubt",
        venue: "Deer Creek/Verizon/Klipsch/Ruoff",
        city: "Noblesville",
        state: "IN",
        date: "8/10/1996",
        notes: "X-Fest 1996",
        sample: "https://www.youtube.com/watch?v=UBVEie8bNdE&list=RDUBVEie8bNdE&start_radio=1",
    },
        {
        performanceNum: "8",
        band: "Seven Mary Three",
        venue: "Deer Creek/Verizon/Klipsch/Ruoff",
        city: "Noblesville",
        state: "IN",
        date: "8/10/1996",
        notes: "X-Fest 1996",
        sample: "https://www.youtube.com/watch?v=l__al8b71lI&list=RDl__al8b71lI&start_radio=1",
    },
        {
        performanceNum: "9",
        band: "Spacehog",
        venue: "Deer Creek/Verizon/Klipsch/Ruoff",
        city: "Noblesville",
        state: "IN",
        date: "8/10/1996",
        notes: "X-Fest 1996",
        sample: "https://www.youtube.com/watch?v=0lhXW1Q_e_0&list=RD0lhXW1Q_e_0&start_radio=1",
    },
        {
        performanceNum: "10",
        band: "Super 8",
        venue: "Deer Creek/Verizon/Klipsch/Ruoff",
        city: "Noblesville",
        state: "IN",
        date: "8/10/1996",
        notes: "X-Fest 1996",
        sample: "https://www.youtube.com/watch?v=X45crqDAFJg&list=PLeH4bva9cvttbnjWQdpyuYiY0hLzWPw0e&index=4",
    },
        {
        performanceNum: "11",
        band: "The Nixons",
        venue: "Deer Creek/Verizon/Klipsch/Ruoff",
        city: "Noblesville",
        state: "IN",
        date: "8/10/1996",
        notes: "X-Fest 1996",
        sample: "https://www.youtube.com/watch?v=c7g2ZihAuUc&list=RDc7g2ZihAuUc&start_radio=1",
    },
        {
        performanceNum: "12",
        band: "The Verve Pipe",
        venue: "Deer Creek/Verizon/Klipsch/Ruoff",
        city: "Noblesville",
        state: "IN",
        date: "8/10/1996",
        notes: "X-Fest 1996",
        sample: "https://www.youtube.com/watch?v=9B88cXlcV1A&list=RD9B88cXlcV1A&start_radio=1",
    },
        {
        performanceNum: "13",
        band: "The Why Store",
        venue: "Deer Creek/Verizon/Klipsch/Ruoff",
        city: "Noblesville",
        state: "IN",
        date: "8/10/1996",
        notes: "X-Fest 1996",
        sample: "https://www.youtube.com/watch?v=h_XYNYmievg&list=RDh_XYNYmievg&start_radio=1",
    },
        {
        performanceNum: "14",
        band: "Bloodhound Gang",
        venue: "Deer Creek/Verizon/Klipsch/Ruoff",
        city: "Noblesville",
        state: "IN",
        date: "6/7/1997",
        notes: "R.O.A.R. Festival",
        sample: "https://www.youtube.com/watch?v=F7OvPTmhtiY&list=RDF7OvPTmhtiY&start_radio=1",
    },
        {
        performanceNum: "15",
        band: "Reverend Horton Heat",
        venue: "Deer Creek/Verizon/Klipsch/Ruoff",
        city: "Noblesville",
        state: "IN",
        date: "6/7/1997",
        notes: "R.O.A.R. Festival",
        sample: "https://www.youtube.com/watch?v=rGFSljyAbvs&list=RDrGFSljyAbvs&start_radio=1",
    },
        {
        performanceNum: "16",
        band: "Sponge",
        venue: "Deer Creek/Verizon/Klipsch/Ruoff",
        city: "Noblesville",
        state: "IN",
        date: "6/7/1997",
        notes: "R.O.A.R. Festival",
        sample: "https://www.youtube.com/watch?v=sObY7GJET7U&list=RDsObY7GJET7U&start_radio=1",
    },
        {
        performanceNum: "17",
        band: "The Nixons",
        venue: "Deer Creek/Verizon/Klipsch/Ruoff",
        city: "Noblesville",
        state: "IN",
        date: "6/7/1997",
        notes: "R.O.A.R. Festival",
        sample: "https://www.youtube.com/watch?v=gDJkJTz7KpQ&list=RDgDJkJTz7KpQ&start_radio=1",
    },
        {
        performanceNum: "18",
        band: "Tonic",
        venue: "Deer Creek/Verizon/Klipsch/Ruoff",
        city: "Noblesville",
        state: "IN",
        date: "6/7/1997",
        notes: "R.O.A.R. Festival",
        sample: "https://www.youtube.com/watch?v=igYSL5osIZM&list=RDigYSL5osIZM&start_radio=1",
    },
        {
        performanceNum: "19",
        band: "Better Than Ezra",
        venue: "Deer Creek/Verizon/Klipsch/Ruoff",
        city: "Noblesville",
        state: "IN",
        date: "8/9/1997",
        notes: "X-Fest 1997",
        sample: "https://www.youtube.com/watch?v=63xJi11bQW4&list=RD63xJi11bQW4&start_radio=1",
    },
        {
        performanceNum: "20",
        band: "Bloodhound Gang",
        venue: "Deer Creek/Verizon/Klipsch/Ruoff",
        city: "Noblesville",
        state: "IN",
        date: "8/9/1997",
        notes: "X-Fest 1997",
        sample: "https://www.youtube.com/watch?v=kBwnoHEl43E&list=RDkBwnoHEl43E&start_radio=1",
    },
        {
        performanceNum: "21",
        band: "Gravity Kills",
        venue: "Deer Creek/Verizon/Klipsch/Ruoff",
        city: "Noblesville",
        state: "IN",
        date: "8/9/1997",
        notes: "X-Fest 1997",
        sample: "https://www.youtube.com/watch?v=IUVheOwDM5I&list=RDIUVheOwDM5I&start_radio=1",
    },
        {
        performanceNum: "22",
        band: "Local H",
        venue: "Deer Creek/Verizon/Klipsch/Ruoff",
        city: "Noblesville",
        state: "IN",
        date: "8/9/1997",
        notes: "X-Fest 1997",
        sample: "https://www.youtube.com/watch?v=5PeU7-hz-AA&list=RD5PeU7-hz-AA&start_radio=1",
    },
        {
        performanceNum: "23",
        band: "Matchbox Twenty",
        venue: "Deer Creek/Verizon/Klipsch/Ruoff",
        city: "Noblesville",
        state: "IN",
        date: "8/9/1997",
        notes: "X-Fest 1997",
        sample: "https://www.youtube.com/watch?v=t2rsf8SiMJY&list=RD8u8gnS1hqiM&index=3",
    },
        {
        performanceNum: "24",
        band: "The Why Store",
        venue: "Deer Creek/Verizon/Klipsch/Ruoff",
        city: "Noblesville",
        state: "IN",
        date: "8/9/1997",
        notes: "X-Fest 1997",
        sample: "https://www.youtube.com/watch?v=3cR8Zaq7fRQ&list=RD3cR8Zaq7fRQ&start_radio=1",
    },
        {
        performanceNum: "25",
        band: "Lynyrd Skynyrd",
        venue: "Deer Creek/Verizon/Klipsch/Ruoff",
        city: "Noblesville",
        state: "IN",
        date: "6/12/1998",
        notes: "",
        sample: "https://www.youtube.com/watch?v=LJrFxnvcWhc&list=RDLJrFxnvcWhc&start_radio=1",
    },
        {
        performanceNum: "26",
        band: "Peter Frampton",
        venue: "Deer Creek/Verizon/Klipsch/Ruoff",
        city: "Noblesville",
        state: "IN",
        date: "6/12/1998",
        notes: "",
        sample: "https://www.youtube.com/watch?v=hUioud7Qtsw&list=RDhUioud7Qtsw&start_radio=1",
    },
        {
        performanceNum: "27",
        band: "John Fogerty",
        venue: "Deer Creek/Verizon/Klipsch/Ruoff",
        city: "Noblesville",
        state: "IN",
        date: "6/13/1998",
        notes: "",
        sample: "https://www.youtube.com/watch?v=_7PUPNxsRQ0&list=RD_7PUPNxsRQ0&start_radio=1",
    },
        {
        performanceNum: "28",
        band: "Athenaeum",
        venue: "Deer Creek/Verizon/Klipsch/Ruoff",
        city: "Noblesville",
        state: "IN",
        date: "8/15/1998",
        notes: "X-Fest 1998",
        sample: "https://www.youtube.com/watch?v=pmdKE9cEsG0&list=RDpmdKE9cEsG0&start_radio=1",
    },
        {
        performanceNum: "29",
        band: "Black Lab",
        venue: "Deer Creek/Verizon/Klipsch/Ruoff",
        city: "Noblesville",
        state: "IN",
        date: "8/15/1998",
        notes: "X-Fest 1998",
        sample: "https://www.youtube.com/watch?v=d_cEEVOieIc&list=RDd_cEEVOieIc&start_radio=1",
    },
        {
        performanceNum: "30",
        band: "Creed",
        venue: "Deer Creek/Verizon/Klipsch/Ruoff",
        city: "Noblesville",
        state: "IN",
        date: "8/15/1998",
        notes: "X-Fest 1998",
        sample: "https://www.youtube.com/watch?v=x51jCGFPQuA&list=RDx51jCGFPQuA&start_radio=1",
    },
        {
        performanceNum: "31",
        band: "Eve 6",
        venue: "Deer Creek/Verizon/Klipsch/Ruoff",
        city: "Noblesville",
        state: "IN",
        date: "8/15/1998",
        notes: "X-Fest 1998",
        sample: "https://www.youtube.com/watch?v=Kn6VkovVUgU&list=RDKn6VkovVUgU&start_radio=1",
    },
        {
        performanceNum: "32",
        band: "Limp Bizkit",
        venue: "Deer Creek/Verizon/Klipsch/Ruoff",
        city: "Noblesville",
        state: "IN",
        date: "8/15/1998",
        notes: "X-Fest 1998",
        sample: "https://www.youtube.com/watch?v=yJ5TsyKcdC4&list=RDyJ5TsyKcdC4&start_radio=1",
    },
        {
        performanceNum: "33",
        band: "Our Lady Peace",
        venue: "Deer Creek/Verizon/Klipsch/Ruoff",
        city: "Noblesville",
        state: "IN",
        date: "8/15/1998",
        notes: "X-Fest 1998",
        sample: "https://www.youtube.com/watch?v=jxxGw64EvIE&list=RDjxxGw64EvIE&start_radio=1",
    },
        {
        performanceNum: "34",
        band: "Stabbing Westward",
        venue: "Deer Creek/Verizon/Klipsch/Ruoff",
        city: "Noblesville",
        state: "IN",
        date: "8/15/1998",
        notes: "X-Fest 1998",
        sample: "https://www.youtube.com/watch?v=5RTy2X_09bo&list=RD5RTy2X_09bo&start_radio=1",
    },
        {
        performanceNum: "35",
        band: "Third Eye Blind",
        venue: "Deer Creek/Verizon/Klipsch/Ruoff",
        city: "Noblesville",
        state: "IN",
        date: "8/15/1998",
        notes: "X-Fest 1998",
        sample: "https://www.youtube.com/watch?v=uEm0ug03Mzw&list=RDuEm0ug03Mzw&start_radio=1",
    },
        {
        performanceNum: "36",
        band: "Roger Waters",
        venue: "Deer Creek/Verizon/Klipsch/Ruoff",
        city: "Noblesville",
        state: "IN",
        date: "8/24/1999",
        notes: "",
        sample: "https://www.youtube.com/watch?v=34ZmKbe5oG4&list=RD34ZmKbe5oG4&start_radio=1",
    },
        {
        performanceNum: "37",
        band: "Muse",
        venue: "Metro",
        city: "Chicago",
        state: "IL",
        date: "4/23/2004",
        notes: "",
        sample: "https://www.youtube.com/watch?v=bwkmNC7ZUUE&list=RDbwkmNC7ZUUE&start_radio=1",
    },
        {  
        performanceNum: "38",
        band: "Gabby La La",
        venue: "Bonnaroo",
        city: "Manchester",
        state: "TN",
        date: "6/9/2005",
        notes: "Bonnaroo 2005",
        sample: "https://www.youtube.com/watch?v=z4BRU39DoU8&list=RDz4BRU39DoU8&start_radio=1",
    },
        {
        performanceNum: "39",
        band: "Dave Matthews Band",
        venue: "Bonnaroo",
        city: "Manchester",
        state: "TN",
        date: "6/10/2005",
        notes: "Bonnaroo 2005",
        sample: "https://www.youtube.com/watch?v=sdfXFZeYGks&list=RDsdfXFZeYGks&start_radio=1",
    },
        {
        performanceNum: "40",
        band: "Jurassic 5",
        venue: "Bonnaroo",
        city: "Manchester",
        state: "TN",
        date: "6/10/2005",
        notes: "Bonnaroo 2005",
        sample: "https://www.youtube.com/watch?v=mcFmo_v81IU&list=RDmcFmo_v81IU&start_radio=1",
    },
        {
        performanceNum: "41",
        band: "Saul Williams",
        venue: "Bonnaroo",
        city: "Manchester",
        state: "TN",
        date: "6/10/2005",
        notes: "Bonnaroo 2005",
        sample: "https://www.youtube.com/watch?v=DhQQseFcTGE&list=RDDhQQseFcTGE&start_radio=1",
    },
        {
        performanceNum: "42",
        band: "The Allman Brothers Band",
        venue: "Bonnaroo",
        city: "Manchester",
        state: "TN",
        date: "6/10/2005",
        notes: "Bonnaroo 2005",
        sample: "https://www.youtube.com/watch?v=Z8zk7XKyoE8&list=RDZ8zk7XKyoE8&start_radio=1",
    },
        {
        performanceNum: "43",
        band: "The Mars Volta",
        venue: "Bonnaroo",
        city: "Manchester",
        state: "TN",
        date: "6/10/2005",
        notes: "Bonnaroo 2005",
        sample: "https://www.youtube.com/watch?v=z26eM4Gr0cA&list=RDz26eM4Gr0cA&start_radio=1",
    },
        {
        performanceNum: "44",
        band: "Iron & Wine",
        venue: "Bonnaroo",
        city: "Manchester",
        state: "TN",
        date: "6/11/2005",
        notes: "Bonnaroo 2005",
        sample: "https://www.youtube.com/watch?v=phjxhBx8MEE&list=RDphjxhBx8MEE&start_radio=1",
    },
        {
        performanceNum: "45",
        band: "Jack Johnson",
        venue: "Bonnaroo",
        city: "Manchester",
        state: "TN",
        date: "6/11/2005",
        notes: "Bonnaroo 2005",
        sample: "https://www.youtube.com/watch?v=u3S6_NtxARY&list=RDu3S6_NtxARY&start_radio=1",
    },
        {
        performanceNum: "46",
        band: "Rilo Kiley",
        venue: "Bonnaroo",
        city: "Manchester",
        state: "TN",
        date: "6/11/2005",
        notes: "Bonnaroo 2005",
        sample: "https://www.youtube.com/watch?v=ItIEXbqzhGg&list=RDItIEXbqzhGg&start_radio=1",
    },
        {
        performanceNum: "47",
        band: "The Black Crowes",
        venue: "Bonnaroo",
        city: "Manchester",
        state: "TN",
        date: "6/11/2005",
        notes: "Bonnaroo 2005",
        sample: "https://www.youtube.com/watch?v=W1tEu_ByGos&list=RDW1tEu_ByGos&start_radio=1",
    },
        {
        performanceNum: "48",
        band: "The Secret Machines",
        venue: "Bonnaroo",
        city: "Manchester",
        state: "TN",
        date: "6/11/2005",
        notes: "Bonnaroo 2005",
        sample: "https://www.youtube.com/watch?v=fOzsHiv0prI&list=RDfOzsHiv0prI&start_radio=1",
    },
        {
        performanceNum: "49",
        band: "Widespread Panic",
        venue: "Bonnaroo",
        city: "Manchester",
        state: "TN",
        date: "6/11/2005",
        notes: "Bonnaroo 2005",
        sample: "https://www.youtube.com/watch?v=HO_7bbEPo-4&list=RDHO_7bbEPo-4&start_radio=1",
    },
        {
        performanceNum: "50",
        band: "Citizen Cope",
        venue: "Bonnaroo",
        city: "Manchester",
        state: "TN",
        date: "6/12/2005",
        notes: "Bonnaroo 2005",
        sample: "https://www.youtube.com/watch?v=MFrzkfUv23E&list=RDMFrzkfUv23E&start_radio=1",
    },
        {
        performanceNum: "51",
        band: "Matisyahu",
        venue: "Bonnaroo",
        city: "Manchester",
        state: "TN",
        date: "6/12/2005",
        notes: "Bonnaroo 2005",
        sample: "https://www.youtube.com/watch?v=e-ysx2rdjx4&list=RDe-ysx2rdjx4&start_radio=1",
    },
        {
        performanceNum: "52",
        band: "Modest Mouse",
        venue: "Bonnaroo",
        city: "Manchester",
        state: "TN",
        date: "6/12/2005",
        notes: "Bonnaroo 2005",
        sample: "https://www.youtube.com/watch?v=hFVHyL0MIVA&list=RDhFVHyL0MIVA&start_radio=1",
    },
        {
        performanceNum: "53",
        band: "Umphrey's McGee",
        venue: "Bonnaroo",
        city: "Manchester",
        state: "TN",
        date: "6/12/2005",
        notes: "Bonnaroo 2005",
        sample: "https://www.youtube.com/watch?v=ybRspL73aQA&list=RDybRspL73aQA&start_radio=1",
    },
        {
        performanceNum: "54",
        band: "Widespread Panic",
        venue: "Bonnaroo",
        city: "Manchester",
        state: "TN",
        date: "6/12/2005",
        notes: "Bonnaroo 2005",
        sample: "https://www.youtube.com/watch?v=PDebe0l6dmw&list=RDPDebe0l6dmw&start_radio=1",
    },
        {
        performanceNum: "55",
        band: "Matt Costa",
        venue: "Bonnaroo",
        city: "Manchester",
        state: "TN",
        date: "6/15/2006",
        notes: "Bonnaroo 2006",
        sample: "https://www.youtube.com/watch?v=KJu9vcT39-M&list=RDKJu9vcT39-M&start_radio=1",
    },
        {
        performanceNum: "56",
        band: "Ben Folds",
        venue: "Bonnaroo",
        city: "Manchester",
        state: "TN",
        date: "6/16/2006",
        notes: "Bonnaroo 2006",
        sample: "https://www.youtube.com/watch?v=aCIzAXc5DpE&list=RDaCIzAXc5DpE&start_radio=1",
    },
        {
        performanceNum: "57",
        band: "Bright Eyes",
        venue: "Bonnaroo",
        city: "Manchester",
        state: "TN",
        date: "6/16/2006",
        notes: "Bonnaroo 2006",
        sample: "https://www.youtube.com/watch?v=2ETCo4sl_90&list=RD2ETCo4sl_90&start_radio=1",
    },
        {
        performanceNum: "58",
        band: "Death Cab For Cutie",
        venue: "Bonnaroo",
        city: "Manchester",
        state: "TN",
        date: "6/16/2006",
        notes: "Bonnaroo 2006",
        sample: "https://www.youtube.com/watch?v=hKtfrRGTboE&list=RDhKtfrRGTboE&start_radio=1",
    },
        {
        performanceNum: "59",
        band: "Oysterhead",
        venue: "Bonnaroo",
        city: "Manchester",
        state: "TN",
        date: "6/16/2006",
        notes: "Bonnaroo 2006",
        sample: "https://www.youtube.com/watch?v=3C-qKFZeXFg&list=RD3C-qKFZeXFg&start_radio=1",
    },
        {
        performanceNum: "60",
        band: "Tom Petty And The Heartbreakers",
        venue: "Bonnaroo",
        city: "Manchester",
        state: "TN",
        date: "6/16/2006",
        notes: "Bonnaroo 2006",
        sample: "https://www.youtube.com/watch?v=PIuAFrLeXfY&list=RDPIuAFrLeXfY&start_radio=1",
    },
        {
        performanceNum: "61",
        band: "Beck",
        venue: "Bonnaroo",
        city: "Manchester",
        state: "TN",
        date: "6/17/2006",
        notes: "Bonnaroo 2006",
        sample: "https://www.youtube.com/watch?v=bvQ3cjz4A5o&list=RDbvQ3cjz4A5o&start_radio=1",
    },
        {
        performanceNum: "62",
        band: "Cypress Hill",
        venue: "Bonnaroo",
        city: "Manchester",
        state: "TN",
        date: "6/17/2006",
        notes: "Bonnaroo 2006",
        sample: "https://www.youtube.com/watch?v=JjiBGdBAVO4&list=RDJjiBGdBAVO4&start_radio=1",
    },
        {
        performanceNum: "63",
        band: "Radiohead",
        venue: "Bonnaroo",
        city: "Manchester",
        state: "TN",
        date: "6/17/2006",
        notes: "Bonnaroo 2006",
        sample: "https://www.youtube.com/watch?v=4IJI6soiQhI&list=RD4IJI6soiQhI&start_radio=1",
    },
        {
        performanceNum: "64",
        band: "Bright Eyes",
        venue: "Wexner Center for the Arts",
        city: "Columbus",
        state: "OH",
        date: "5/20/2007",
        notes: "",
        sample: "https://www.youtube.com/watch?v=ETdDMHx7oGU&list=RDETdDMHx7oGU&start_radio=1",
    },
        {
        performanceNum: "65",
        band: "Gillian Welch",
        venue: "Wexner Center for the Arts",
        city: "Columbus",
        state: "OH",
        date: "5/20/2007",
        notes: "",
        sample: "https://www.youtube.com/watch?v=B8aH4cRdplE&list=RDB8aH4cRdplE&start_radio=1",
    },
        {
        performanceNum: "66",
        band: "Cold War Kids",
        venue: "Bonnaroo",
        city: "Manchester",
        state: "TN",
        date: "6/15/2007",
        notes: "Bonnaroo 2007",
        sample: "https://www.youtube.com/watch?v=UyI5Noafito&list=RDUyI5Noafito&start_radio=1",
    },
        {
        performanceNum: "67",
        band: "DJ Shadow",
        venue: "Bonnaroo",
        city: "Manchester",
        state: "TN",
        date: "6/15/2007",
        notes: "Bonnaroo 2007",
        sample: "https://www.youtube.com/watch?v=BEqHME6XUi8&list=RDBEqHME6XUi8&start_radio=1",
    },
        {
        performanceNum: "68",
        band: "Tool",
        venue: "Bonnaroo",
        city: "Manchester",
        state: "TN",
        date: "6/15/2007",
        notes: "Bonnaroo 2007",
        sample: "https://www.youtube.com/watch?v=M1tIH55Bo8k&list=RDM1tIH55Bo8k&start_radio=1",
    },
        {
        performanceNum: "69",
        band: "Damien Rice",
        venue: "Bonnaroo",
        city: "Manchester",
        state: "TN",
        date: "6/16/2007",
        notes: "Bonnaroo 2007",
        sample: "https://www.youtube.com/watch?v=QRRAxbEPU0c&list=RDQRRAxbEPU0c&start_radio=1",
    },
        {
        performanceNum: "70",
        band: "Spoon",
        venue: "Bonnaroo",
        city: "Manchester",
        state: "TN",
        date: "6/16/2007",
        notes: "Bonnaroo 2007",
        sample: "https://www.youtube.com/watch?v=5710OAhwkUw&list=RD5710OAhwkUw&start_radio=1",
    },
        {
        performanceNum: "71",
        band: "The Flaming Lips",
        venue: "Bonnaroo",
        city: "Manchester",
        state: "TN",
        date: "6/16/2007",
        notes: "Bonnaroo 2007",
        sample: "https://www.youtube.com/watch?v=5zYOKFjpm9s&list=RD5zYOKFjpm9s&start_radio=1",
    },
        {
        performanceNum: "72",
        band: "The Police",
        venue: "Bonnaroo",
        city: "Manchester",
        state: "TN",
        date: "6/16/2007",
        notes: "Bonnaroo 2007",
        sample: "https://www.youtube.com/watch?v=Cdu3a2arXdw&list=RDCdu3a2arXdw&start_radio=1",
    },
        {
        performanceNum: "73",
        band: "The White Stripes",
        venue: "Bonnaroo",
        city: "Manchester",
        state: "TN",
        date: "6/17/2007",
        notes: "Bonnaroo 2007",
        sample: "https://www.youtube.com/watch?v=j_4RRpTg1Cg&list=RDj_4RRpTg1Cg&start_radio=1",
    },
        {
        performanceNum: "74",
        band: "Battles",
        venue: "Bonnaroo",
        city: "Manchester",
        state: "TN",
        date: "6/12/2008",
        notes: "Bonnaroo 2008",
        sample: "https://www.youtube.com/watch?v=lBlVeieFqKc&list=RDlBlVeieFqKc&start_radio=1",
    },
        {
        performanceNum: "75",
        band: "Lez Zeppelin",
        venue: "Bonnaroo",
        city: "Manchester",
        state: "TN",
        date: "6/12/2008",
        notes: "Bonnaroo 2008",
        sample: "https://www.youtube.com/watch?v=pIzk9VLWXT4&list=RDpIzk9VLWXT4&start_radio=1",
    },
        {
        performanceNum: "76",
        band: "MGMT",
        venue: "Bonnaroo",
        city: "Manchester",
        state: "TN",
        date: "6/12/2008",
        notes: "Bonnaroo 2008",
        sample: "https://www.youtube.com/watch?v=4qb8AfVvhUI&list=RD4qb8AfVvhUI&start_radio=1",
    },
        {
        performanceNum: "77",
        band: "Vampire Weekend",
        venue: "Bonnaroo",
        city: "Manchester",
        state: "TN",
        date: "6/12/2008",
        notes: "Bonnaroo 2008",
        sample: "https://www.youtube.com/watch?v=_9osMhzQmcA&list=RD_9osMhzQmcA&start_radio=1",
    },
        {
        performanceNum: "78",
        band: "Jose Gonzales",
        venue: "Bonnaroo",
        city: "Manchester",
        state: "TN",
        date: "6/13/2008",
        notes: "Bonnaroo 2008",
        sample: "https://www.youtube.com/watch?v=IbBIhiweYDE&list=RDIbBIhiweYDE&start_radio=1",
    },
        {
        performanceNum: "79",
        band: "Metallica",
        venue: "Bonnaroo",
        city: "Manchester",
        state: "TN",
        date: "6/13/2008",
        notes: "Bonnaroo 2008",
        sample: "https://www.youtube.com/watch?v=E0ozmU9cJDg&list=RDE0ozmU9cJDg&start_radio=1",
    },
        {
        performanceNum: "80",
        band: "MSTRKRFT",
        venue: "Bonnaroo",
        city: "Manchester",
        state: "TN",
        date: "6/13/2008",
        notes: "Bonnaroo 2008",
        sample: "https://www.youtube.com/watch?v=C72EARB8rYs&list=RDC72EARB8rYs&start_radio=1",
    },
        {
        performanceNum: "81",
        band: "Rilo Kiley",
        venue: "Bonnaroo",
        city: "Manchester",
        state: "TN",
        date: "6/13/2008",
        notes: "Bonnaroo 2008",
        sample: "https://www.youtube.com/watch?v=Hn7Ldn7liGU&list=RDHn7Ldn7liGU&start_radio=1",
    },
        {
        performanceNum: "82",
        band: "The Raconteurs",
        venue: "Bonnaroo",
        city: "Manchester",
        state: "TN",
        date: "6/13/2008",
        notes: "Bonnaroo 2008",
        sample: "https://www.youtube.com/watch?v=KmgEe30e34Q&list=RDKmgEe30e34Q&start_radio=1",
    },
        {
        performanceNum: "83",
        band: "Ghostland Observatory",
        venue: "Bonnaroo",
        city: "Manchester",
        state: "TN",
        date: "6/14/2008",
        notes: "Bonnaroo 2008",
        sample: "https://www.youtube.com/watch?v=SwV_MMhj2X4&list=RDSwV_MMhj2X4&start_radio=1",
    },
        {
        performanceNum: "84",
        band: "Iron & Wine",
        venue: "Bonnaroo",
        city: "Manchester",
        state: "TN",
        date: "6/14/2008",
        notes: "Bonnaroo 2008",
        sample: "https://www.youtube.com/watch?v=RGVmhrfQqzg&list=RDRGVmhrfQqzg&start_radio=1",
    },
        {
        performanceNum: "85",
        band: "Pearl Jam",
        venue: "Bonnaroo",
        city: "Manchester",
        state: "TN",
        date: "6/14/2008",
        notes: "Bonnaroo 2008",
        sample: "https://www.youtube.com/watch?v=qgaRVvAKoqQ&list=RDqgaRVvAKoqQ&start_radio=1",
    },
        {
        performanceNum: "86",
        band: "Sigur Ros",
        venue: "Bonnaroo",
        city: "Manchester",
        state: "TN",
        date: "6/14/2008",
        notes: "Bonnaroo 2008",
        sample: "https://www.youtube.com/watch?v=7fEUUnXDnbk&list=RD7fEUUnXDnbk&start_radio=1",
    },
        {
        performanceNum: "87",
        band: "Aimee Mann",
        venue: "Bonnaroo",
        city: "Manchester",
        state: "TN",
        date: "6/15/2008",
        notes: "Bonnaroo 2008",
        sample: "https://www.youtube.com/watch?v=hdT0WJQG5R8&list=RDhdT0WJQG5R8&start_radio=1",
    },
        {
        performanceNum: "88",
        band: "Broken Social Scene",
        venue: "Bonnaroo",
        city: "Manchester",
        state: "TN",
        date: "6/15/2008",
        notes: "Bonnaroo 2008",
        sample: "https://www.youtube.com/watch?v=KSrwV4A7mZc&list=RDKSrwV4A7mZc&start_radio=1",
    },
        {
        performanceNum: "89",
        band: "Death Cab For Cutie",
        venue: "Bonnaroo",
        city: "Manchester",
        state: "TN",
        date: "6/15/2008",
        notes: "Bonnaroo 2008",
        sample: "https://www.youtube.com/watch?v=hKtfrRGTboE&list=RDhKtfrRGTboE&start_radio=1",
    },
        {
        performanceNum: "90",
        band: "Rogue Wave",
        venue: "Bonnaroo",
        city: "Manchester",
        state: "TN",
        date: "6/15/2008",
        notes: "Bonnaroo 2008",
        sample: "https://www.youtube.com/watch?v=amhdBa0ltWw&list=RDamhdBa0ltWw&start_radio=1",
    },
        {
        performanceNum: "91",
        band: "Widespread Panic",
        venue: "Bonnaroo",
        city: "Manchester",
        state: "TN",
        date: "6/15/2008",
        notes: "Bonnaroo 2008",
        sample: "https://www.youtube.com/watch?v=Rza5eWjYAPs&list=RDRza5eWjYAPs&start_radio=1",
    },
        {
        performanceNum: "92",
        band: "Grizzly Bear",
        venue: "Deer Creek/Verizon/Klipsch/Ruoff",
        city: "Noblesville",
        state: "IN",
        date: "8/3/2008",
        notes: "",
        sample: "https://www.youtube.com/watch?v=eziWqoGEekY&list=RDeziWqoGEekY&start_radio=1",
    },
        {
        performanceNum: "93",
        band: "Radiohead",
        venue: "Deer Creek/Verizon/Klipsch/Ruoff",
        city: "Noblesville",
        state: "IN",
        date: "8/3/2008",
        notes: "",
        sample: "https://www.youtube.com/watch?v=1On-ZHfTWOo&list=RD1On-ZHfTWOo&start_radio=1",
    },
        {
        performanceNum: "94",
        band: "Boris",
        venue: "Allen County War Memorial Coliseum",
        city: "Fort Wayne",
        state: "IN",
        date: "11/18/2008",
        notes: "",
        sample: "https://www.youtube.com/watch?v=uQMvzDQw3wY&list=RDuQMvzDQw3wY&start_radio=1",
    },
        {
        performanceNum: "95",
        band: "Nine Inch Nails",
        venue: "Allen County War Memorial Coliseum",
        city: "Fort Wayne",
        state: "IN",
        date: "11/18/2008",
        notes: "",
        sample: "https://www.youtube.com/watch?v=Iprm5f78CA0&list=RDIprm5f78CA0&start_radio=1",
    },
        {
        performanceNum: "96",
        band: "Jane's Addiction",
        venue: "Deer Creek/Verizon/Klipsch/Ruoff",
        city: "Noblesville",
        state: "IN",
        date: "5/30/2009",
        notes: "",
        sample: "https://www.youtube.com/watch?v=QimlMkyR4fI&list=RDQimlMkyR4fI&start_radio=1",
    },
        {
        performanceNum: "97",
        band: "Nine Inch Nails",
        venue: "Deer Creek/Verizon/Klipsch/Ruoff",
        city: "Noblesville",
        state: "IN",
        date: "5/30/2009",
        notes: "",
        sample: "https://www.youtube.com/watch?v=ABvjpZp1N2Y&list=RDABvjpZp1N2Y&start_radio=1",
    },
        {
        performanceNum: "98",
        band: "Chairlift",
        venue: "Bonnaroo",
        city: "Manchester",
        state: "TN",
        date: "6/11/2009",
        notes: "Bonnaroo 2009",
        sample: "https://www.youtube.com/watch?v=GrM5SOGw9T8&list=RDGrM5SOGw9T8&start_radio=1",
    },
        {
        performanceNum: "99",
        band: "Passion Pit",
        venue: "Bonnaroo",
        city: "Manchester",
        state: "TN",
        date: "6/11/2009",
        notes: "Bonnaroo 2009",
        sample: "https://www.youtube.com/watch?v=na1OdO30Yp8&list=RDna1OdO30Yp8&start_radio=1",
    },
            {
        performanceNum: "100",
        band: "Beastie Boys",
        venue: "Bonnaroo",
        city: "Manchester",
        state: "TN",
        date: "6/12/2009",
        notes: "Bonnaroo 2009",
        sample: "https://www.youtube.com/watch?v=2WHFTRArC44&list=RD2WHFTRArC44&start_radio=1",
    },
        {
        performanceNum: "101",
        band: "Crystal Castles",
        venue: "Bonnaroo",
        city: "Manchester",
        state: "TN",
        date: "6/12/2009",
        notes: "Bonnaroo 2009",
        sample: "https://www.youtube.com/watch?v=t2hRQ2yuRto&list=RDt2hRQ2yuRto&start_radio=1",
    },
        {
        performanceNum: "102",
        band: "Girl Talk",
        venue: "Bonnaroo",
        city: "Manchester",
        state: "TN",
        date: "6/12/2009",
        notes: "Bonnaroo 2009",
        sample: "https://www.youtube.com/watch?v=4bMM7tGV9MI&list=RD4bMM7tGV9MI&start_radio=1",
    },
        {
        performanceNum: "103",
        band: "Phish",
        venue: "Bonnaroo",
        city: "Manchester",
        state: "TN",
        date: "6/12/2009",
        notes: "Bonnaroo 2009",
        sample: "https://www.youtube.com/watch?v=VHQfg59Kp5Q&list=RDVHQfg59Kp5Q&start_radio=1",
    },
        {
        performanceNum: "104",
        band: "Phoenix",
        venue: "Bonnaroo",
        city: "Manchester",
        state: "TN",
        date: "6/12/2009",
        notes: "Bonnaroo 2009",
        sample: "https://www.youtube.com/watch?v=byrJTtTLBVU&list=RDbyrJTtTLBVU&start_radio=1",
    },
        {
        performanceNum: "105",
        band: "Bon Iver",
        venue: "Bonnaroo",
        city: "Manchester",
        state: "TN",
        date: "6/13/2009",
        notes: "Bonnaroo 2009",
        sample: "https://www.youtube.com/watch?v=8NstorpFnjM&list=RD8NstorpFnjM&start_radio=1",
    },
        {
        performanceNum: "106",
        band: "Nine Inch Nails",
        venue: "Bonnaroo",
        city: "Manchester",
        state: "TN",
        date: "6/13/2009",
        notes: "Bonnaroo 2009",
        sample: "https://www.youtube.com/watch?v=JX-Vlrpv8qI&list=RDJX-Vlrpv8qI&start_radio=1",
    },
        {
        performanceNum: "107",
        band: "The Decemberists",
        venue: "Bonnaroo",
        city: "Manchester",
        state: "TN",
        date: "6/13/2009",
        notes: "Bonnaroo 2009",
        sample: "https://www.youtube.com/watch?v=jnwRewQ--QM&list=RDjnwRewQ--QM&start_radio=1",
    },
        {
        performanceNum: "108",
        band: "The Mars Volta",
        venue: "Bonnaroo",
        city: "Manchester",
        state: "TN",
        date: "6/13/2009",
        notes: "Bonnaroo 2009",
        sample: "https://www.youtube.com/watch?v=Zg6svO2AQHw&list=RDZg6svO2AQHw&start_radio=1",
    },
        {
        performanceNum: "109",
        band: "Yeasayer",
        venue: "Bonnaroo",
        city: "Manchester",
        state: "TN",
        date: "6/13/2009",
        notes: "Bonnaroo 2009",
        sample: "https://www.youtube.com/watch?v=olzw8qi6Ptw&list=RDolzw8qi6Ptw&start_radio=1",
    },
        {
        performanceNum: "110",
        band: "Andrew Bird",
        venue: "Bonnaroo",
        city: "Manchester",
        state: "TN",
        date: "6/14/2009",
        notes: "Bonnaroo 2009",
        sample: "https://www.youtube.com/watch?v=vY59Wo8DM5U&list=RDvY59Wo8DM5U&start_radio=1",
    },
        {
        performanceNum: "111",
        band: "Band Of Horses",
        venue: "Bonnaroo",
        city: "Manchester",
        state: "TN",
        date: "6/14/2009",
        notes: "Bonnaroo 2009",
        sample: "https://www.youtube.com/watch?v=HJ9qLSpuJ7M&list=RDHJ9qLSpuJ7M&start_radio=1",
    },
        {
        performanceNum: "112",
        band: "Phish",
        venue: "Bonnaroo",
        city: "Manchester",
        state: "TN",
        date: "6/14/2009",
        notes: "Bonnaroo 2009",
        sample: "https://www.youtube.com/watch?v=kI0bCtaozP0&list=RDkI0bCtaozP0&start_radio=1",
    },
        {
        performanceNum: "113",
        band: "Snoop Dogg",
        venue: "Bonnaroo",
        city: "Manchester",
        state: "TN",
        date: "6/14/2009",
        notes: "Bonnaroo 2009",
        sample: "https://www.youtube.com/watch?v=AQLwmsVLoiA&list=RDAQLwmsVLoiA&start_radio=1",
    },
        {
        performanceNum: "114",
        band: "Blitzen Trapper",
        venue: "Bonnaroo",
        city: "Manchester",
        state: "TN",
        date: "6/10/2010",
        notes: "Bonnaroo 2010",
        sample: "https://www.youtube.com/watch?v=bvQMdOb79R4&list=RDbvQMdOb79R4&start_radio=1",
    },
        {
        performanceNum: "115",
        band: "Here We Go Magic",
        venue: "Bonnaroo",
        city: "Manchester",
        state: "TN",
        date: "6/10/2010",
        notes: "Bonnaroo 2010",
        sample: "https://www.youtube.com/watch?v=WQtWN5fvowI&list=RDWQtWN5fvowI&start_radio=1",
    },
        {
        performanceNum: "116",
        band: "Manchester Orchestra",
        venue: "Bonnaroo",
        city: "Manchester",
        state: "TN",
        date: "6/10/2010",
        notes: "Bonnaroo 2010",
        sample: "https://www.youtube.com/watch?v=ba0GF7uqSio&list=RDba0GF7uqSio&start_radio=1",
    },
        {
        performanceNum: "117",
        band: "Neon Indian",
        venue: "Bonnaroo",
        city: "Manchester",
        state: "TN",
        date: "6/10/2010",
        notes: "Bonnaroo 2010",
        sample: "https://www.youtube.com/watch?v=XcpFhfN4-jM&list=RDXcpFhfN4-jM&start_radio=1",
    },
        {
        performanceNum: "118",
        band: "The Entrance Band",
        venue: "Bonnaroo",
        city: "Manchester",
        state: "TN",
        date: "6/10/2010",
        notes: "Bonnaroo 2010",
        sample: "https://www.youtube.com/watch?v=sFkasPNdGi4&list=RDsFkasPNdGi4&start_radio=1",
    },
        {
        performanceNum: "119",
        band: "The XX",
        venue: "Bonnaroo",
        city: "Manchester",
        state: "TN",
        date: "6/10/2010",
        notes: "Bonnaroo 2010",
        sample: "https://www.youtube.com/watch?v=-Jp2wNF1rkM&list=RD-Jp2wNF1rkM&start_radio=1",
    },
        {
        performanceNum: "120",
        band: "Bassnectar",
        venue: "Bonnaroo",
        city: "Manchester",
        state: "TN",
        date: "6/11/2010",
        notes: "Bonnaroo 2010",
        sample: "https://www.youtube.com/watch?v=JRftXCiqfQ8&list=RDJRftXCiqfQ8&start_radio=1",
    },
        {
        performanceNum: "121",
        band: "Damian Marley & Nas",
        venue: "Bonnaroo",
        city: "Manchester",
        state: "TN",
        date: "6/11/2010",
        notes: "Bonnaroo 2010",
        sample: "https://www.youtube.com/watch?v=jAfLlXf-0Eo&list=RDjAfLlXf-0Eo&start_radio=1",
    },
        {
        performanceNum: "122",
        band: "Edward Sharpe & The Magnetic Zeroes",
        venue: "Bonnaroo",
        city: "Manchester",
        state: "TN",
        date: "6/11/2010",
        notes: "Bonnaroo 2010",
        sample: "https://www.youtube.com/watch?v=-zpEMkKJd0M&list=RD-zpEMkKJd0M&start_radio=1",
    },
        {
        performanceNum: "123",
        band: "Jay Electronica",
        venue: "Bonnaroo",
        city: "Manchester",
        state: "TN",
        date: "6/11/2010",
        notes: "Bonnaroo 2010",
        sample: "https://www.youtube.com/watch?v=-1tlyGcAHbU",
    },
        {
        performanceNum: "124",
        band: "Kings Of Leon",
        venue: "Bonnaroo",
        city: "Manchester",
        state: "TN",
        date: "6/11/2010",
        notes: "Bonnaroo 2010",
        sample: "https://www.youtube.com/watch?v=dfboIlgQiQQ&list=RDdfboIlgQiQQ&start_radio=1",
    },
        {
        performanceNum: "125",
        band: "LCD Soundsystem",
        venue: "Bonnaroo",
        city: "Manchester",
        state: "TN",
        date: "6/11/2010",
        notes: "Bonnaroo 2010",
        sample: "https://www.youtube.com/watch?v=fMrwcvy9maI&list=RDfMrwcvy9maI&start_radio=1",
    },
        {
        performanceNum: "126",
        band: "Les Claypool",
        venue: "Bonnaroo",
        city: "Manchester",
        state: "TN",
        date: "6/11/2010",
        notes: "Bonnaroo 2010",
        sample: "https://www.youtube.com/watch?v=13bHgZPtJ7Q&list=RD13bHgZPtJ7Q&start_radio=1",
    },
        {
        performanceNum: "127",
        band: "The Flaming Lips",
        venue: "Bonnaroo",
        city: "Manchester",
        state: "TN",
        date: "6/11/2010",
        notes: "Bonnaroo 2010",
        sample: "https://www.youtube.com/watch?v=aKiVSuDEF2c&list=RDaKiVSuDEF2c&start_radio=1",
    },
        {
        performanceNum: "128",
        band: "The National",
        venue: "Bonnaroo",
        city: "Manchester",
        state: "TN",
        date: "6/11/2010",
        notes: "Bonnaroo 2010",
        sample: "https://www.youtube.com/watch?v=8WRWno_c_W8&list=RD8WRWno_c_W8&start_radio=1",
    },
        {
        performanceNumL: "129",
        band: "Circa Survive",
        venue: "Bonnaroo",
        city: "Manchester",
        state: "TN",
        date: "6/12/2010",
        notes: "Bonnaroo 2010",
        sample: "https://www.youtube.com/watch?v=IZU7xXgxRx4&list=RDIZU7xXgxRx4&start_radio=1",
    },
        {
        performanceNum: "130",
        band: "Dave Rawlings Machine",
        venue: "Bonnaroo",
        city: "Manchester",
        state: "TN",
        date: "6/12/2010",
        notes: "Bonnaroo 2010",
        sample: "https://www.youtube.com/watch?v=YVOrbMnv1es&list=RDYVOrbMnv1es&start_radio=1",
    },
        {
        performanceNum: "131",
        band: "Deadmau5",
        venue: "Bonnaroo",
        city: "Manchester",
        state: "TN",
        date: "6/12/2010",
        notes: "Bonnaroo 2010",
        sample: "https://www.youtube.com/watch?v=pb-EwykPTv8&list=RDpb-EwykPTv8&start_radio=1",
    },
        {
        performanceNum: "132",
        band: "Jay-Z",
        venue: "Bonnaroo",
        city: "Manchester",
        state: "TN",
        date: "6/12/2010",
        notes: "Bonnaroo 2010",
        sample: "https://www.youtube.com/watch?v=gA2I9Nkn-7Y&list=RDgA2I9Nkn-7Y&start_radio=1",
    },
        {
        performanceNum: "133",
        band: "Stevie Wonder",
        venue: "Bonnaroo",
        city: "Manchester",
        state: "TN",
        date: "6/12/2010",
        notes: "Bonnaroo 2010",
        sample: "https://www.youtube.com/watch?v=ftdZ363R9kQ&list=RDftdZ363R9kQ&start_radio=1",
    },
        {
        performanceNum: "134",
        band: "The Avett Brothers",
        venue: "Bonnaroo",
        city: "Manchester",
        state: "TN",
        date: "6/12/2010",
        notes: "Bonnaroo 2010",
        sample: "https://www.youtube.com/watch?v=JjwlDNwJRpE&list=RDJjwlDNwJRpE&start_radio=1",
    },
        {
        performanceNum: "135",
        band: "The Dead Weather",
        venue: "Bonnaroo",
        city: "Manchester",
        state: "TN",
        date: "6/12/2010",
        notes: "Bonnaroo 2010",
        sample: "https://www.youtube.com/watch?v=1g_fc4fLqXk&list=RD1g_fc4fLqXk&start_radio=1",
    },
        {
        performanceNum: "136",
        band: "Weezer",
        venue: "Bonnaroo",
        city: "Manchester",
        state: "TN",
        date: "6/12/2010",
        notes: "Bonnaroo 2010",
        sample: "https://www.youtube.com/watch?v=1_XnVHDA0fI&list=RD1_XnVHDA0fI&start_radio=1",
    },
        {
        performanceNum: "137",
        band: "Blues Traveler",
        venue: "Bonnaroo",
        city: "Manchester",
        state: "TN",
        date: "6/13/2010",
        notes: "Bonnaroo 2010",
        sample: "https://www.youtube.com/watch?v=6AhhcZBfnBc&list=RD6AhhcZBfnBc&start_radio=1",
    },
        {
        performanceNum: "138",
        band: "Dave Matthews Band",
        venue: "Bonnaroo",
        city: "Manchester",
        state: "TN",
        date: "6/13/2010",
        notes: "Bonnaroo 2010",
        sample: "https://www.youtube.com/watch?v=EOmMKmGnnB4&list=RDEOmMKmGnnB4&start_radio=1",
    },
        {
        performanceNum: "139",
        band: "John Fogerty",
        venue: "Bonnaroo",
        city: "Manchester",
        state: "TN",
        date: "6/13/2010",
        notes: "Bonnaroo 2010",
        sample: "https://www.youtube.com/watch?v=CzX6SuEldbY&list=RDCzX6SuEldbY&start_radio=1",
    },
        {
        performanceNum: "140",
        band: "Phoenix",
        venue: "Bonnaroo",
        city: "Manchester",
        state: "TN",
        date: "6/13/2010",
        notes: "Bonnaroo 2010",
        sample: "https://www.youtube.com/watch?v=uF3reVVUbio&list=RDuF3reVVUbio&start_radio=1",
    },
        {
        performanceNum: "141",
        band: "Alt-J",
        venue: "Bonnaroo",
        city: "Manchester",
        state: "TN",
        date: "6/13/2010",
        notes: "Bonnaroo 2013",
        sample: "https://www.youtube.com/watch?v=kT6pFsVA6hA&list=RDkT6pFsVA6hA&start_radio=1",
    },
        {
        performanceNum: "142",
        band: "Father John Misty",
        venue: "Bonnaroo",
        city: "Manchester",
        state: "TN",
        date: "6/13/2010",
        notes: "Bonnaroo 2013",
        sample: "https://www.youtube.com/watch?v=Ao29iZ566Bk&list=RDAo29iZ566Bk&start_radio=1",
    },
        {
        performanceNum: "143",
        band: "Purity Ring",
        venue: "Bonnaroo",
        city: "Manchester",
        state: "TN",
        date: "6/13/2010",
        notes: "Bonnaroo 2013",
        sample: "https://www.youtube.com/watch?v=ETbGpGJNVLM&list=RDETbGpGJNVLM&start_radio=1",
    },
        {
        performanceNum: "144",
        band: "Twenty One Pilots",
        venue: "Bonnaroo",
        city: "Manchester",
        state: "TN",
        date: "6/13/2010",
        notes: "Bonnaroo 2013",
        sample: "https://www.youtube.com/watch?v=jgVoJTFtLNs&list=RDjgVoJTFtLNs&start_radio=1",
    },
        {
        performanceNum: "145",
        band: "Glen Hansard",
        venue: "Bonnaroo",
        city: "Manchester",
        state: "TN",
        date: "6/14/2013",
        notes: "Bonnaroo 2013",
        sample: "https://www.youtube.com/watch?v=Oj1sYaQitnE&list=RDOj1sYaQitnE&start_radio=1",
    },
        {
        performanceNum: "146",
        band: "Grizzly Bear",
        venue: "Bonnaroo",
        city: "Manchester",
        state: "TN",
        date: "6/14/2013",
        notes: "Bonnaroo 2013",
        sample: "https://www.youtube.com/watch?v=gQfHDDNXckE&list=RDgQfHDDNXckE&start_radio=1",
    },
        {
        performanceNum: "147",
        band: "Paul McCartney",
        venue: "Bonnaroo",
        city: "Manchester",
        state: "TN",
        date: "6/14/2013",
        notes: "Bonnaroo 2013",
        sample: "https://www.youtube.com/watch?v=mQER0A0ej0M&list=RDmQER0A0ej0M&start_radio=1",
    },
        {
        performanceNum: "148",
        band: "Wu-Tang Clan",
        venue: "Bonnaroo",
        city: "Manchester",
        state: "TN",
        date: "6/14/2013",
        notes: "Bonnaroo 2013",
        sample: "https://www.youtube.com/watch?v=0R8BMY12JSU&list=RD0R8BMY12JSU&start_radio=1",
    },
        {
        performanceNum: "149",
        band: "Bjork",
        venue: "Bonnaroo",
        city: "Manchester",
        state: "TN",
        date: "6/15/2013",
        notes: "Bonnaroo 2013",
        sample: "https://www.youtube.com/watch?v=FqfQXJSvbo4&list=RDFqfQXJSvbo4&start_radio=1",
    },
            {
        performanceNum: "150",
        band: "Lord Huron",
        venue: "Bonnaroo",
        city: "Manchester",
        state: "TN",
        date: "6/15/2013",
        notes: "Bonnaroo 2013",
        sample: "https://www.youtube.com/watch?v=GBPVu5aqnAI&list=RDGBPVu5aqnAI&start_radio=1",
    },
        {
        performanceNum: "151",
        band: "Mumford & Sons",
        venue: "Bonnaroo",
        city: "Manchester",
        state: "TN",
        date: "6/15/2013",
        notes: "Bonnaroo 2013",
        sample: "https://www.youtube.com/watch?v=pD9KOw8uFis&list=RDpD9KOw8uFis&start_radio=1",
    },
        {
        performanceNum: "152",
        band: "Nas",
        venue: "Bonnaroo",
        city: "Manchester",
        state: "TN",
        date: "6/15/2013",
        notes: "Bonnaroo 2013",
        sample: "https://www.youtube.com/watch?v=hI8A14Qcv68&list=RDhI8A14Qcv68&start_radio=1",
    },
        {
        performanceNum: "153",
        band: "Portugal. The Man",
        venue: "Bonnaroo",
        city: "Manchester",
        state: "TN",
        date: "6/15/2013",
        notes: "Bonnaroo 2013",
        sample: "https://www.youtube.com/watch?v=8cLOctIPd00&list=RD8cLOctIPd00&start_radio=1",
    },
        {
        performanceNum: "154",
        band: "The National",
        venue: "Bonnaroo",
        city: "Manchester",
        state: "TN",
        date: "6/16/2013",
        notes: "Bonnaroo 2013",
        sample: "https://www.youtube.com/watch?v=IprgVNlFIqM&list=RDIprgVNlFIqM&start_radio=1",
    },
        {
        performanceNum: "155",
        band: "Tom Petty & The Heartbreakers",
        venue: "Bonnaroo",
        city: "Manchester",
        state: "TN",
        date: "6/16/2013",
        notes: "Bonnaroo 2013",
        sample: "https://www.youtube.com/watch?v=YtZeVx5Om4c&list=RDYtZeVx5Om4c&start_radio=1",
    },
        {
        performanceNum: "156",
        band: "Twenty One Pilots",
        venue: "Bogart's",
        city: "Cincinnati",
        state: "OH",
        date: "10/26/2013",
        notes: "",
        sample: "https://www.youtube.com/watch?v=w1Smzzw_w7Q&list=RDw1Smzzw_w7Q&start_radio=1",
    },
        {
        performanceNum: "157",
        band: "LCD Soundsystem",
        venue: "Aragon Ballroom",
        city: "Chicago",
        state: "IL",
        date: "11/6/2017",
        notes: "",
        sample: "https://www.youtube.com/watch?v=OoA0cTC228M&list=RDOoA0cTC228M&start_radio=1",
    },
        {
        performanceNum: "158",
        band: "Junun",
        venue: "US Bank Arena",
        city: "Cincinnati",
        state: "OH",
        date: "7/25/2018",
        notes: "",
        sample: "",
    },
        {
        performanceNum: "159",
        band: "Radiohead",
        venue: "US Bank Arena",
        city: "Cincinnati",
        state: "OH",
        date: "7/25/2018",
        notes: "",
        sample: "https://www.youtube.com/watch?v=TR2HPSjcJ7I&list=RDTR2HPSjcJ7I&start_radio=1",
    },
        {
        performanceNum: "160",
        band: "The Smashing Pumpkins",
        venue: "Banker's Life/Gainbridge Fieldhouse",
        city: "Indianapolis",
        state: "IN",
        date: "8/17/2018",
        notes: "",
        sample: "https://www.youtube.com/watch?v=mQq_BbyNEpM&list=RDmQq_BbyNEpM&start_radio=1",
    },
        {
        performanceNum: "161",
        band: "Courtney Barnett",
        venue: "TCU Ampitheater/White River Park",
        city: "Indianapolis",
        state: "IN",
        date: "6/26/2019",
        notes: "",
        sample: "https://www.youtube.com/watch?v=ZSrRgf8n4O0&list=RDZSrRgf8n4O0&start_radio=1",
    },
        {
        performanceNum: "162",
        band: "The National",
        venue: "TCU Ampitheater/White River Park",
        city: "Indianapolis",
        state: "IN",
        date: "6/26/2019",
        notes: "",
        sample: "https://www.youtube.com/watch?v=8fzwUtna4eg&list=RD8fzwUtna4eg&start_radio=1",
    },
        {
        performanceNum: "163",
        band: "Killing Joke",
        venue: "Banker's Life/Gainbridge Fieldhouse",
        city: "Indianapolis",
        state: "IN",
        date: "11/2/2019",
        notes: "",
        sample: "https://www.youtube.com/watch?v=0MUE3AXIiXc&list=RD0MUE3AXIiXc&start_radio=1",
    },
        {
        performanceNum: "164",
        band: "Tool",
        venue: "Banker's Life/Gainbridge Fieldhouse",
        city: "Indianapolis",
        state: "IN",
        date: "11/2/2019",
        notes: "",
        sample: "https://www.youtube.com/watch?v=-DuAAmHpGbw&list=RD-DuAAmHpGbw&start_radio=1",
    },
        {
        performanceNum: "165",
        band: "Deafheaven",
        venue: "Thalia Hall",
        city: "Chicago",
        state: "IL",
        date: "3/14/2022",
        notes: "",
        sample: "https://www.youtube.com/watch?v=RWyVhIBmdGw&list=RDRWyVhIBmdGw&start_radio=1",
    },
        {
        performanceNum: "166",
        band: "Holy Fawn",
        venue: "Thalia Hall",
        city: "Chicago",
        state: "IL",
        date: "3/14/2022",
        notes: "",
        sample: "https://www.youtube.com/watch?v=TgDPUQDOdDs&list=RDTgDPUQDOdDs&start_radio=1",
    },
        {
        performanceNum: "167",
        band: "Midwife",
        venue: "Thalia Hall",
        city: "Chicago",
        state: "IL",
        date: "3/14/2022",
        notes: "",
        sample: "https://www.youtube.com/watch?v=rLINAmnp7eg&list=RDrLINAmnp7eg&start_radio=1",
    },
        {
        performanceNum: "168",
        band: "Matt Talbott",
        venue: "Loud And Clear Studio",
        city: "Paducah",
        state: "KY",
        date: "4/17/2022",
        notes: "",
        sample: "",
    },
        {
        performanceNum: "169",
        band: "Deftones",
        venue: "TCU Ampitheater/White River Park",
        city: "Indianapolis",
        state: "IN",
        date: "5/10/2022",
        notes: "",
        sample: "https://www.youtube.com/watch?v=dd_461ZrJb8&list=RDdd_461ZrJb8&start_radio=1",
    },
        {
        performanceNum: "170",
        band: "Gojira",
        venue: "TCU Ampitheater/White River Park",
        city: "Indianapolis",
        state: "IN",
        date: "5/10/2022",
        notes: "",
        sample: "https://www.youtube.com/watch?v=tdVjuS_FhI4&list=RDtdVjuS_FhI4&start_radio=1",
    },
        {
        performanceNum: "171",
        band: "Garbage",
        venue: "Deer Creek/Verizon/Klipsch/Ruoff",
        city: "Noblesville",
        state: "IN",
        date: "6/17/2022",
        notes: "",
        sample: "https://www.youtube.com/watch?v=nMqslcTBRf8&list=RDnMqslcTBRf8&start_radio=1",
    },
        {
        performanceNum: "172",
        band: "Tears For Fears",
        venue: "Deer Creek/Verizon/Klipsch/Ruoff",
        city: "Noblesville",
        state: "IN",
        date: "6/17/2022",
        notes: "",
        sample: "https://www.youtube.com/watch?v=luOwnc5bqho&list=RDluOwnc5bqho&start_radio=1",
    },
        {
        performanceNum: "173",
        band: "Gin Blossoms",
        venue: "TCU Ampitheater/White River Park",
        city: "Indianapolis",
        state: "IN",
        date: "7/1/2022",
        notes: "",
        sample: "https://www.youtube.com/watch?v=XDjbg-WDimc&list=RDXDjbg-WDimc&start_radio=1",
    },
        {
        performanceNum: "174",
        band: "Toad The Wet Sprocket",
        venue: "TCU Ampitheater/White River Park",
        city: "Indianapolis",
        state: "IN",
        date: "7/1/2022",
        notes: "",
        sample: "https://www.youtube.com/watch?v=Gj-XN2TD7_Y&list=RDGj-XN2TD7_Y&start_radio=1",
    },
        {
        performanceNum: "175",
        band: "Rage Against The Machine",
        venue: "Rocket Mortgage Fieldhouse",
        city: "Cleveland",
        state: "OH",
        date: "7/27/2022",
        notes: "",
        sample: "https://www.youtube.com/watch?v=ctiKD8jtvV8&list=RDctiKD8jtvV8&start_radio=1",
    },
        {
        performanceNum: "176",
        band: "Run The Jewels",
        venue: "Rocket Mortgage Fieldhouse",
        city: "Cleveland",
        state: "OH",
        date: "7/27/2022",
        notes: "",
        sample: "https://www.youtube.com/watch?v=OG4ROzg78Bo&list=RDOG4ROzg78Bo&start_radio=1",
    },
        {
        performanceNum: "177",
        band: "Interpol",
        venue: "TCU Ampitheater/White River Park",
        city: "Indianapolis",
        state: "IN",
        date: "9/8/2022",
        notes: "",
        sample: "https://www.youtube.com/watch?v=NwYKAsbx8SU&list=RDNwYKAsbx8SU&start_radio=1",
    },
        {
        performanceNum: "178",
        band: "Spoon",
        venue: "TCU Ampitheater/White River Park",
        city: "Indianapolis",
        state: "IN",
        date: "9/8/2022",
        notes: "",
        sample: "https://www.youtube.com/watch?v=teXA8N3aF9M&list=RDteXA8N3aF9M&start_radio=1",
    },
        {
        performanceNum: "179",
        band: "Indigo Sparkle",
        venue: "TCU Ampitheater/White River Park",
        city: "Indianapolis",
        state: "IN",
        date: "9/18/2022",
        notes: "",
        sample: "https://www.youtube.com/watch?v=w9QlXL1c93Y&list=RDw9QlXL1c93Y&start_radio=1",
    },
        {
        performanceNum: "180",
        band: "The National",
        venue: "TCU Ampitheater/White River Park",
        city: "Indianapolis",
        state: "IN",
        date: "9/18/2022",
        notes: "",
        sample: "https://www.youtube.com/watch?v=DLOS5msrReA&list=RDDLOS5msrReA&start_radio=1",
    },
        {
        performanceNum: "181",
        band: "Ministry",
        venue: "Blossom Music Center",
        city: "Cleveland",
        state: "OH",
        date: "9/24/2022",
        notes: "",
        sample: "https://www.youtube.com/watch?v=imqvLToWH7k&list=RDimqvLToWH7k&start_radio=1",
    },
        {
        performanceNum: "182",
        band: "Nine Inch Nails",
        venue: "Blossom Music Center",
        city: "Cleveland",
        state: "OH",
        date: "9/24/2022",
        notes: "",
        sample: "https://www.youtube.com/watch?v=Kr-uzvTBAlY&list=RDKr-uzvTBAlY&start_radio=1",
    },
        {
        performanceNum: "183",
        band: "Nitzer Ebb",
        venue: "Blossom Music Center",
        city: "Cleveland",
        state: "OH",
        date: "9/24/2022",
        notes: "",
        sample: "https://www.youtube.com/watch?v=R9PimZnRO5I&list=RDR9PimZnRO5I&start_radio=1",
    },
        {
        performanceNum: "184",
        band: "Holy Fawn",
        venue: "Hi-Fi",
        city: "Indianapolis",
        state: "IN",
        date: "7/29/2023",
        notes: "Post Festival 2023",
        sample: "https://www.youtube.com/watch?v=bWCeLXH2P9A&list=RDbWCeLXH2P9A&start_radio=1",
    },
        {
        performanceNum: "185",
        band: "Kowloon Walled City",
        venue: "Hi-Fi",
        city: "Indianapolis",
        state: "IN",
        date: "7/29/2023",
        notes: "Post Festival 2023",
        sample: "https://www.youtube.com/watch?v=i2at7UFupP0&list=RDi2at7UFupP0&start_radio=1",
    },
        {
        performanceNum: "186",
        band: "Shipwreck Karpathos",
        venue: "Hi-Fi",
        city: "Indianapolis",
        state: "IN",
        date: "7/29/2023",
        notes: "Post Festival 2023",
        sample: "https://www.youtube.com/watch?v=ncpwUsyQc2w&list=RDncpwUsyQc2w&start_radio=1",
    },
        {
        performanceNum: "187",
        band: "Soft Blue Shimmer",
        venue: "Hi-Fi",
        city: "Indianapolis",
        state: "IN",
        date: "7/29/2023",
        notes: "Post Festival 2023",
        sample: "https://www.youtube.com/watch?v=fohmJkOHtY4&list=RDfohmJkOHtY4&start_radio=1",
    },
        {
        performanceNum: "188",
        band: "Modest Mouse",
        venue: "TCU Ampitheater/White River Park",
        city: "Indianapolis",
        state: "IN",
        date: "8/29/2023",
        notes: "",
        sample: "https://www.youtube.com/watch?v=jdzpWfliYM0&list=RDjdzpWfliYM0&start_radio=1",
    },
        {
        performanceNum: "189",
        band: "Pixies",
        venue: "TCU Ampitheater/White River Park",
        city: "Indianapolis",
        state: "IN",
        date: "8/29/2023",
        notes: "",
        sample: "https://www.youtube.com/watch?v=tVCUAXOBF7w&list=RDtVCUAXOBF7w&start_radio=1",
    },
        {
        performanceNum: "190",
        band: "Gaerea",
        venue: "The Vogue",
        city: "Indianapolis",
        state: "IN",
        date: "12/2/2024",
        notes: "",
        sample: "https://www.youtube.com/watch?v=4yArVDm3cqE&list=RD4yArVDm3cqE&start_radio=1",
    },
        {
        performanceNum: "191",
        band: "Zeal & Ardor",
        venue: "The Vogue",
        city: "Indianapolis",
        state: "IN",
        date: "12/2/2024",
        notes: "",
        sample: "https://www.youtube.com/watch?v=PujFyEqUxlQ&list=PLGY7CF1o5PA2J3-HVx7pIdPR_2YZa70Bw&index=3",
    },
        {
        performanceNum: "192",
        band: "Alcest",
        venue: "Metro",
        city: "Chicago",
        state: "IL",
        date: "3/18/2025",
        notes: "",
        sample: "https://www.youtube.com/watch?v=e-kW-rxzJ_0&list=RDe-kW-rxzJ_0&start_radio=1",
    },
        {
        performanceNum: "193",
        band: "MONO",
        venue: "Metro",
        city: "Chicago",
        state: "IL",
        date: "3/18/2025",
        notes: "",
        sample: "https://www.youtube.com/watch?v=co5gy_2uOEY&list=RDco5gy_2uOEY&start_radio=1",
    },
        {
        performanceNum: "194",
        band: "Deafheaven",
        venue: "The Vogue",
        city: "Indianapolis",
        state: "IN",
        date: "9/12/2025",
        notes: "",
        sample: "https://www.youtube.com/watch?v=QWb15MwIaSY&list=RDQWb15MwIaSY&start_radio=1",
    },
        {
        performanceNum: "195",
        band: "Harm's Way",
        venue: "The Vogue",
        city: "Indianapolis",
        state: "IN",
        date: "9/12/2025",
        notes: "",
        sample: "https://www.youtube.com/watch?v=F5fFr437eog&list=RDF5fFr437eog&start_radio=1",
    },
        {
        performanceNum: "196",
        band: "Chapterhouse",
        venue: "Aragon Ballroom",
        city: "Chicago",
        state: "IL",
        date: "5/23/2026",
        notes: "Slide Away 2026",
        sample: "https://www.youtube.com/watch?v=5PsN_DfnHQU&list=RD5PsN_DfnHQU&start_radio=1",
    },
        {
        performanceNum: "197",
        band: "Hum",
        venue: "Aragon Ballroom",
        city: "Chicago",
        state: "IL",
        date: "5/23/2026",
        notes: "Slide Away 2026",
        sample: "https://www.youtube.com/watch?v=lSHBtsPxEP8&list=RDlSHBtsPxEP8&start_radio=1",
    },
        {
        performanceNum: "198",
        band: "Nothing",
        venue: "Aragon Ballroom",
        city: "Chicago",
        state: "IL",
        date: "5/23/2026",
        notes: "Slide Away 2026",
        sample: "https://www.youtube.com/watch?v=3_7Gn8hmEJA&list=PLE74ZAjkuuPX5KXRasRiSawA-zF8DnE03&index=2",
    },
        {
        performanceNum: "199",
        band: "Conjurer",
        venue: "Black Circle",
        city: "Indianapolis",
        state: "IN",
        date: "6/1/2026",
        notes: "",
        sample: "https://www.youtube.com/watch?v=p4x8M4s3-qs&list=RDp4x8M4s3-qs&start_radio=1",
    },
            {
        performanceNum: "200",
        band: "Sadness",
        venue: "Black Circle",
        city: "Indianapolis",
        state: "IN",
        date: "6/1/2026",
        notes: "",
        sample: "https://www.youtube.com/watch?v=swbg76x9S4g&list=RDswbg76x9S4g&start_radio=1",
    },
]







///////////////////////////////////////////////////////////////////////////////////////////
///////////////////////////////////////////////////////////////////////////////////////////
///////////////////////////////////////////////////////////////////////////////////////////
///////////////////////////////////////////////////////////////////////////////////////////
///////////////////////////////////////////////////////////////////////////////////////////
///////////////////////////////////////////////////////////////////////////////////////////
///////////////////////////////////////////////////////////////////////////////////////////
///////////////////////////////////////////////////////////////////////////////////////////
///////////////////////////////////////////////////////////////////////////////////////////
///////////////////////////////////////////////////////////////////////////////////////////
///////////////////////////////////////////////////////////////////////////////////////////
///////////////////////////////////////////////////////////////////////////////////////////
///////////////////////////////////////////////////////////////////////////////////////////
///////////////////////////////////////////////////////////////////////////////////////////
///////////////////////////////////////////////////////////////////////////////////////////
///////////////////////////////////////////////////////////////////////////////////////////


//search div, user can enter search parameters to return a list of performances that meet the criteria
const searchTable = function () {
    let table = document.createElement('table');
    let thead = document.createElement('thead');
    let tbody = document.createElement('tbody');
    let headerRow = document.createElement('tr');

    ['Band', 'Venue', 'City', 'State', 'Date', 'Notes'].forEach(headerText => {
    let header = document.createElement('th');
    header.textContent = headerText;
    headerRow.appendChild(header);
    });

    table.appendChild(thead);
    thead.appendChild(headerRow);
    table.appendChild(tbody);
         
    let findInfo = document.querySelector("#showSearch").value;
    const selectedSearch = new Array();
    performance.forEach((performance)=> {
    if (performance.band.includes(findInfo))
        selectedSearch.push(performance);
    if (performance.venue.includes(findInfo))
        selectedSearch.push(performance);
    if (performance.city.includes(findInfo))
        selectedSearch.push(performance);
    if (performance.state.includes(findInfo))
        selectedSearch.push(performance);
    if (performance.date.includes(findInfo))
        selectedSearch.push(performance);
    if (performance.notes.includes(findInfo))
        selectedSearch.push(performance);
    if (performance.sample.includes(findInfo))
        selectedSearch.push(performance);
    });

    let selectedSearchSet = new Set(selectedSearch);

    selectedSearchSet.forEach(selectedSearchSet => {
        let row = tbody.insertRow();
        let bandCell = row.insertCell(0);
        bandCell.innerHTML = '<a href="' + selectedSearchSet.sample + '" target="_blank">' + selectedSearchSet.band + '</a>';
        let venueCell = row.insertCell(1);
        venueCell.textContent = selectedSearchSet.venue;
        let cityCell = row.insertCell(2);
        cityCell.textContent = selectedSearchSet.city;
        let stateCell = row.insertCell(3);
        stateCell.textContent = selectedSearchSet.state;
        let dateCell = row.insertCell(4);
        dateCell.textContent = selectedSearchSet.date;
        let notesCell = row.insertCell(5);
        notesCell.textContent = selectedSearchSet.notes;
    });

        const list = document.getElementById("topDiv");
        while (list.hasChildNodes()) {
        list.removeChild(list.firstChild);
    };

        document.getElementById("topDiv").appendChild(table);
        document.getElementById("showSearch").value = "";
    };
  
//clears the tables
const clearTable = function () {
        const list = document.getElementById("topDiv");
        while (list.hasChildNodes()) {
        list.removeChild(list.firstChild);}
    };

